# Generated by Django 5.2.9 on 2026-01-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_reviewed', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_reviewed'],
            },
        ),
    ]
