# Generated by Django 5.2.9 on 2025-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('striker', models.CharField(max_length=255)),
                ('target_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('crew_number', models.IntegerField(blank=True, null=True)),
                ('number_killed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
