# Generated by Django 5.2.9 on 2025-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_strike_image_url_strike_target_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='dvids_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
