# Generated by Django 5.2.9 on 2026-01-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_strike_dvids_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strike',
            old_name='location',
            new_name='location_label',
        ),
        migrations.AddField(
            model_name='strike',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='strike',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='strike',
            name='location_uncertainty_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
