# Generated by Django 5.2.9 on 2026-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_location_strike_location_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
    ]
