# Generated by Django 5.2.9 on 2026-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_strike_location_lat_alter_strike_location_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='summary',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
