# Generated by Django 5.2.9 on 2026-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_strike_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='image_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
