# Generated by Django 5.2.9 on 2026-01-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_strike_image_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_reviewed', models.DateField()),
            ],
            options={
                'ordering': ['-last_reviewed'],
            },
        ),
    ]
