# Generated by Django 5.2.9 on 2026-01-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
