# Generated by Django 5.2.9 on 2026-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_source'),
        ('sources', '0002_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='sources',
            field=models.ManyToManyField(blank=True, to='sources.source'),
        ),
    ]
