# Generated by Django 5.2.9 on 2026-01-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_strike_sources'),
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='existing_strike_pk',
        ),
        migrations.AddField(
            model_name='submission',
            name='existing_strike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.strike'),
        ),
    ]
