# Generated by Django 5.2.9 on 2026-01-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_remove_submission_existing_strike_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='new_strike_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
